// ============================================================
// 書き出す成果物（Terraform一式）に同梱するファイルの本文。
//
// ここに並ぶ文字列は「UIの文言」ではなく「生成物の中身」なので、
// UIの辞書（i18n.ts）ではなくこのファイルが持ちます。
// core が生成する main.tf のコメントと同じく、ロケール（ja/en）に
// 応じて本文を切り替えます。
// ============================================================

import { ENV_IDS } from '@zuform/core/types';
import type { Locale } from '@zuform/core/types';

/** 利用者が自由に追記するためのファイル（Zuformは再生成時も触らない） */
export function buildCustomTf(locale: Locale): string {
  if (locale === 'en') {
    return [
      '# ============================================================',
      '# custom.tf — your own additions (Zuform never overwrites this file)',
      '#',
      '# Terraform loads and merges every .tf file in the same directory,',
      '# so you can add resources here without touching main.tf.',
      '# Regenerating main.tf from the diagram leaves this file untouched.',
      '#',
      '# To change only an attribute of a generated resource, use an override:',
      '#   create a file named main_override.tf, repeat the same resource block,',
      '#   and write only the attributes you want to change.',
      '#   Example: change just the size of an RDS instance',
      '#     resource "aws_db_instance" "users_db" {',
      '#       instance_class = "db.r6g.large"',
      '#     }',
      '# ============================================================',
      '',
    ].join('\n');
  }
  return [
    '# ============================================================',
    '# custom.tf — 自分の追記用ファイル（Zuformは上書きしません）',
    '#',
    '# Terraformは同じディレクトリの .tf ファイルをすべて読み込んで',
    '# 結合するため、main.tf に手を入れずにここへ追加できます。',
    '# 図を更新して main.tf を再生成しても、このファイルは無傷です。',
    '#',
    '# 生成済みリソースの「属性だけ」変えたい場合は override が便利:',
    '#   main_override.tf というファイルを作り、同名のresourceブロックで',
    '#   変えたい属性だけを書くと、その属性だけが上書きされます。',
    '#   例: RDSのサイズだけ変更する',
    '#     resource "aws_db_instance" "users_db" {',
    '#       instance_class = "db.r6g.large"',
    '#     }',
    '# ============================================================',
    '',
  ].join('\n');
}

/** environments/ 直下に置く案内（環境ごとのディレクトリ構成の説明） */
export function buildEnvironmentsReadme(locale: Locale): string {
  const tree = ['```', 'environments/', ...ENV_IDS.map((e) => `├── ${e}/  (main.tf + custom.tf)`), '```'];
  if (locale === 'en') {
    return [
      '# Per-environment Terraform',
      '',
      'Environment-specific code generated by Zuform.',
      '',
      ...tree,
      '',
      'Change into an environment directory and run terraform init / plan / apply.',
      'Each environment keeps its own tfstate, so experimenting in DEV never affects production.',
      '',
      '## Editing by hand',
      '',
      '- `main.tf` is regenerated by the tool. Avoid editing it directly',
      "- Put extra resources and settings in each environment's `custom.tf` (regeneration leaves it alone)",
      '- To change attributes of a generated resource, use `main_override.tf` (Terraform overrides)',
    ].join('\n');
  }
  return [
    '# 環境別Terraform',
    '',
    'Zuform で生成された環境別のコードです。',
    '',
    ...tree,
    '',
    '各環境のディレクトリに移動して terraform init / plan / apply を実行してください。',
    '環境ごとにtfstateが分かれるため、DEVでの試行錯誤が本番に影響しません。',
    '',
    '## 手で編集したい場合',
    '',
    '- `main.tf` はツールが再生成するファイルです。直接編集は避けてください',
    '- 追加のリソースや設定は各環境の `custom.tf` に書いてください（再生成の影響を受けません）',
    '- 生成済みリソースの属性変更は `main_override.tf`（override機能）が使えます',
  ].join('\n');
}
